version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    environment:
      POSTGRES_DB: intel_lab
      POSTGRES_USER: timescale
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U timescale"]
      interval: 10s
      timeout: 5s
      retries: 5

  data_loader:
    build: .
    volumes:
      - ./data:/data
    environment:
      DB_HOST: timescaledb
      DB_PORT: 5432
      DB_NAME: intel_lab
      DB_USER: timescale
      DB_PASSWORD: password123
    depends_on:
      timescaledb:
        condition: service_healthy

volumes:
  timescale_data:
